version: '3'
services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:1.12
    ports:
      - "8113:80"
    networks:
      default:
        ipv4_address: ${DEFAULT_NETWORK_BASE_ADDRESS}2
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
      - ./../:/var/www/html
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: ./php
      args:
        - HOST_UID=${HOST_UID}
    user: ${HOST_UID}
    networks:
      default:
        ipv4_address: ${DEFAULT_NETWORK_BASE_ADDRESS}3
    volumes:
      - ./../:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql/mysql-server:5.7
    networks:
      default:
        ipv4_address: ${DEFAULT_NETWORK_BASE_ADDRESS}4
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/config.conf:/etc/my.cnf
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME}-nodejs
    image: node:8.12
    ports:
      - "22:22"
    networks:
      default:
        ipv4_address: ${DEFAULT_NETWORK_BASE_ADDRESS}6
    volumes:
      - ./nodejs/server.js:/etc/server.js
      - ./../:/var/www/html
    working_dir: /var/www/html
    command: node /etc/server.js
    user: ${HOST_UID}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DEFAULT_NETWORK_BASE_ADDRESS}0/16
